/**
 * packages/core/src/sandbox.ts
 *
 * Isolation helpers:
 *  - buildWsbConfig(): generates a Windows Sandbox (.wsb) configuration that
 *    starts a portable copy of the app inside a disposable VM. Everything
 *    written inside the sandbox is discarded when it closes.
 *  - describeIsolation(): the summary shown BEFORE a profile starts
 *    (folders, clipboard, camera, microphone, devices, network route).
 *
 * Windows Sandbox requires Windows 10/11 Pro, Enterprise or Education with the
 * "Windows Sandbox" optional feature enabled and virtualisation turned on.
 * If it is not available, the UI offers the "restricted" mode instead.
 */
import type { Profile } from './profiles';
import { effectiveSettings } from './privacy';

export interface WsbOptions {
  /** Host folder containing the portable app (mapped READ-ONLY). */
  appHostDir: string;
  /** Executable name inside appHostDir. */
  exeName: string;
  /** Optional host folder shared read-write for downloads. Omit = downloads stay inside the sandbox. */
  downloadsHostDir?: string;
  networking: boolean;
  clipboard: boolean;
  audioInput: boolean;
  videoInput: boolean;
  /** Extra arguments passed to the app inside the sandbox. */
  args: string[];
  memoryMB?: number;
}

const SANDBOX_USER_HOME = 'C:\\Users\\WDAGUtilityAccount';
export const SANDBOX_APP_DIR = `${SANDBOX_USER_HOME}\\OctoApp`;
export const SANDBOX_DOWNLOADS_DIR = `${SANDBOX_USER_HOME}\\Downloads\\Shared`;
export const SANDBOX_DATA_DIR = `${SANDBOX_USER_HOME}\\OctoData`;

function xml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&apos;');
}

/** Quote a Windows command-line argument (CommandLineToArgvW rules). */
export function quoteWinArg(arg: string): string {
  if (arg && !/[\s"]/.test(arg)) return arg;
  let out = '"';
  let backslashes = 0;
  for (const ch of arg) {
    if (ch === '\\') { backslashes++; continue; }
    if (ch === '"') { out += '\\'.repeat(backslashes * 2 + 1) + '"'; backslashes = 0; continue; }
    out += '\\'.repeat(backslashes) + ch;
    backslashes = 0;
  }
  return out + '\\'.repeat(backslashes * 2) + '"';
}

export function buildWsbConfig(o: WsbOptions): string {
  const enable = (b: boolean) => (b ? 'Enable' : 'Disable');
  const folders = [
    `    <MappedFolder>\n      <HostFolder>${xml(o.appHostDir)}</HostFolder>\n      <SandboxFolder>${xml(SANDBOX_APP_DIR)}</SandboxFolder>\n      <ReadOnly>true</ReadOnly>\n    </MappedFolder>`,
  ];
  if (o.downloadsHostDir) {
    folders.push(
      `    <MappedFolder>\n      <HostFolder>${xml(o.downloadsHostDir)}</HostFolder>\n      <SandboxFolder>${xml(SANDBOX_DOWNLOADS_DIR)}</SandboxFolder>\n      <ReadOnly>false</ReadOnly>\n    </MappedFolder>`,
    );
  }
  const cmd = [quoteWinArg(`${SANDBOX_APP_DIR}\\${o.exeName}`), ...o.args.map(quoteWinArg)].join(' ');
  return [
    '<Configuration>',
    '  <!-- Generated by Octo.su. Everything inside the sandbox is deleted when it closes. -->',
    '  <vGPU>Disable</vGPU>',
    `  <Networking>${enable(o.networking)}</Networking>`,
    `  <AudioInput>${enable(o.audioInput)}</AudioInput>`,
    `  <VideoInput>${enable(o.videoInput)}</VideoInput>`,
    `  <ClipboardRedirection>${enable(o.clipboard)}</ClipboardRedirection>`,
    '  <PrinterRedirection>Disable</PrinterRedirection>',
    '  <ProtectedClient>Enable</ProtectedClient>',
    o.memoryMB ? `  <MemoryInMB>${Math.max(2048, Math.floor(o.memoryMB))}</MemoryInMB>` : '',
    '  <MappedFolders>',
    ...folders,
    '  </MappedFolders>',
    '  <LogonCommand>',
    `    <Command>${xml(cmd)}</Command>`,
    '  </LogonCommand>',
    '</Configuration>',
    '',
  ].filter((l) => l !== '').join('\r\n');
}

export interface IsolationItem {
  /** i18n key for the label. */
  labelKey: string;
  /** Display value (already localised by caller) or i18n key prefixed with "t:". */
  value: string;
  state: 'allowed' | 'blocked' | 'limited' | 'info';
}

/** What a profile will be able to access - shown before launch (spec §6). */
export function describeIsolation(p: Profile, env: { downloadsDir: string; windowsSandboxAvailable: boolean; vpnDetected: boolean }): IsolationItem[] {
  const s = effectiveSettings(p.protection);
  const inWsb = p.sandbox.mode === 'windows-sandbox' && env.windowsSandboxAvailable;
  const items: IsolationItem[] = [];
  items.push({
    labelKey: 'iso.mode',
    value: `t:iso.mode.${p.sandbox.mode === 'windows-sandbox' && !env.windowsSandboxAvailable ? 'wsbUnavailable' : p.sandbox.mode}`,
    state: p.sandbox.mode === 'none' ? 'info' : 'limited',
  });
  items.push({
    labelKey: 'iso.folders',
    value: inWsb ? (p.sandbox.shareDownloads ? env.downloadsDir : 't:iso.folders.sandboxOnly') : env.downloadsDir,
    state: 'limited',
  });
  items.push({
    labelKey: 'iso.clipboard',
    value: `t:iso.clipboard.${p.sandbox.clipboard}`,
    state: p.sandbox.clipboard === 'allow' ? 'allowed' : p.sandbox.clipboard === 'block' ? 'blocked' : 'limited',
  });
  items.push({ labelKey: 'iso.camera', value: p.sandbox.camera ? 't:state.askFirst' : 't:state.blocked', state: p.sandbox.camera ? 'allowed' : 'blocked' });
  items.push({ labelKey: 'iso.microphone', value: p.sandbox.microphone ? 't:state.askFirst' : 't:state.blocked', state: p.sandbox.microphone ? 'allowed' : 'blocked' });
  items.push({ labelKey: 'iso.devices', value: p.sandbox.externalDevices ? 't:state.askFirst' : 't:state.blocked', state: p.sandbox.externalDevices ? 'allowed' : 'blocked' });
  let route = 't:iso.route.direct';
  if (p.kind === 'tor' || s.level === 'tor') route = 't:iso.route.tor';
  else if (p.network.mode === 'proxy' && p.network.proxyRules) route = 't:iso.route.proxy';
  else if (p.network.mode === 'system') route = 't:iso.route.system';
  items.push({ labelKey: 'iso.route', value: route, state: 'info' });
  items.push({ labelKey: 'iso.vpn', value: env.vpnDetected ? 't:iso.vpn.detected' : 't:iso.vpn.none', state: 'info' });
  // Windows Sandbox is a disposable VM with its own virtual switch: VPN filters on the
  // host (kill switch in particular) can block its network. Say so BEFORE launching.
  if (inWsb && env.vpnDetected) {
    items.push({ labelKey: 'iso.network', value: 't:sandbox.vpnWarning', state: 'info' });
  }
  if (inWsb) {
    items.push({ labelKey: 'iso.status', value: 't:sandbox.testVersion', state: 'info' });
  }
  items.push({ labelKey: 'iso.admin', value: 't:iso.admin.never', state: 'blocked' });
  return items;
}
