/**
 * packages/core/src/update-public-key.ts
 *
 * Ed25519 public key used to verify signed update manifests (latest.json.sig).
 *
 * This file is GENERATED by `npm run keygen` (tools/update-keygen.mjs).
 * The matching PRIVATE key is written to ./keys/ which is git-ignored and must
 * be stored offline / in the CI secret store - NEVER commit it.
 *
 * While this value is empty the updater reports "not configured" and refuses
 * to download anything (fail closed).
 */
export const UPDATE_PUBLIC_KEY_PEM = '';
