// tools/update-keygen.mjs
//
// Generates the Ed25519 key pair used to sign update manifests (latest.json).
//
//   npm run keygen                -> creates keys/update-private-key.pem (+ public key)
//   npm run keygen -- --force     -> replaces an existing key (all installed copies
//                                    will then REJECT updates signed with the new key
//                                    until they are reinstalled manually!)
//
// Environment:
//   OCTO_KEY_PASSPHRASE  optional; when set the private key PEM is encrypted
//                        (PKCS#8, AES-256-CBC with scrypt-derived key by OpenSSL).
//
// Output:
//   keys/update-private-key.pem   PRIVATE - git-ignored. Move it offline / into a CI secret.
//   keys/update-public-key.pem    public copy (for reference)
//   packages/core/src/update-public-key.ts   public key compiled into both apps
//   scripts/lib/update-public-key.pem         public key for install.bat (Node.js fallback)
//
// No custom crypto: key generation uses Node's OpenSSL-backed crypto module.
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { root } from './lib/load-core.mjs';

const force = process.argv.includes('--force');
const keysDir = path.join(root, 'keys');
const privFile = path.join(keysDir, 'update-private-key.pem');
const pubFile = path.join(keysDir, 'update-public-key.pem');
const tsFile = path.join(root, 'packages', 'core', 'src', 'update-public-key.ts');
// Copy for scripts\install.bat on machines without an installed app (verified with Node.js).
const scriptsPem = path.join(root, 'scripts', 'lib', 'update-public-key.pem');

function main() {
  if (fs.existsSync(privFile) && !force) {
    console.error(`A private key already exists: ${path.relative(root, privFile)}\n` +
      'Refusing to overwrite it. Use --force only if you really want to rotate the key.');
    process.exit(2);
  }
  // Make sure keys/ is ignored before writing anything secret.
  const gi = fs.readFileSync(path.join(root, '.gitignore'), 'utf8');
  if (!/^keys\/$/m.test(gi)) {
    console.error('.gitignore does not contain "keys/" - aborting to avoid committing the private key.');
    process.exit(3);
  }
  const passphrase = process.env.OCTO_KEY_PASSPHRASE || undefined;
  const { publicKey, privateKey } = crypto.generateKeyPairSync('ed25519', {
    publicKeyEncoding: { type: 'spki', format: 'pem' },
    privateKeyEncoding: passphrase
      ? { type: 'pkcs8', format: 'pem', cipher: 'aes-256-cbc', passphrase }
      : { type: 'pkcs8', format: 'pem' },
  });
  fs.mkdirSync(keysDir, { recursive: true });
  fs.writeFileSync(privFile, privateKey, { mode: 0o600 });
  fs.writeFileSync(pubFile, publicKey);
  fs.mkdirSync(path.dirname(scriptsPem), { recursive: true });
  fs.writeFileSync(scriptsPem, publicKey);

  const ts = `/**
 * packages/core/src/update-public-key.ts
 *
 * Ed25519 public key used to verify signed update manifests (latest.json.sig).
 *
 * This file is GENERATED by \`npm run keygen\` (tools/update-keygen.mjs) on ${new Date().toISOString().slice(0, 10)}.
 * The matching PRIVATE key is in ./keys/ which is git-ignored and must be
 * stored offline / in the CI secret store - NEVER commit it.
 *
 * While this value is empty the updater reports "not configured" and refuses
 * to download anything (fail closed).
 */
export const UPDATE_PUBLIC_KEY_PEM = ${JSON.stringify(publicKey.trim())};
`;
  fs.writeFileSync(tsFile, ts);
  const fp = crypto.createHash('sha256').update(crypto.createPublicKey(publicKey).export({ type: 'spki', format: 'der' })).digest('hex');
  console.log('Update signing key generated.');
  console.log(`  private: ${path.relative(root, privFile)} ${passphrase ? '(encrypted with OCTO_KEY_PASSPHRASE)' : '(NOT encrypted - consider OCTO_KEY_PASSPHRASE)'}`);
  console.log(`  public : ${path.relative(root, tsFile)}`);
  console.log(`  SHA-256 fingerprint of public key: ${fp}`);
  console.log('Next: rebuild both apps (npm run build) so they contain the public key, and back up the private key offline.');
}

try {
  main();
} catch (err) {
  console.error('keygen failed:', err?.message ?? err);
  process.exit(1);
}
