/**
 * Click and campaign identifiers that are removed from the address of a page the user opens.
 * Names are lowercase and matched case-sensitively, so a rewritten address never matches again.
 */
export const TRACKING_PARAMS: readonly string[] = [
  'utm_source',
  'utm_medium',
  'utm_campaign',
  'utm_term',
  'utm_content',
  'utm_id',
  'utm_source_platform',
  'utm_creative_format',
  'utm_marketing_tactic',
  'fbclid',
  'gclid',
  'gclsrc',
  'dclid',
  'gbraid',
  'wbraid',
  'msclkid',
  'yclid',
  'twclid',
  'ttclid',
  'li_fat_id',
  'igshid',
  'mc_eid',
  'mc_cid',
  'mkt_tok',
  'vero_id',
  'oly_anon_id',
  'oly_enc_id',
  '_hsenc',
  '_hsmi',
  '__hssc',
  '__hstc',
  '__hsfp',
];
